### ISSUE TITLE
[FEATURE REQUEST] Parametrize which leds are displayed

### ISSUE THREAD

**Issue by gladykov** [oco2000/xfce4-kbdleds-plugin#11]
In my use case, I need only Caps Lock indicator, as caps lock led broke on physical keyboard.

Feature request here, is to add configuration option to the widget, enabling showing / hiding particular led indicators.

**Comment by ovoronin-suki-ai** [comment]
You can do it in Properties dialog

**Comment by oco2000** [comment]
You can do it in Properties dialog now

**Comment by gladykov** [comment]
Yay! Thank you very much sir!
