### ISSUE TITLE
Components are installed in the wrong locations

### ISSUE THREAD

**Issue by MatNieuw** [oco2000/xfce4-kbdleds-plugin#2]
With the default ¨ ./configure --prefix=/usr " components get installed at wrong locations, at least for Mint 20.1 and Manjaro, compared to for instance the xfce4-battery-plugin. 
Running configure as " ./configure --prefix=/usr --datarootdir=/usr/share --libdir=/usr/lib/x86_64-linux-gnu " .
If this should be the default for current distro's, can de ./configure defaults be changed? I am not familiar with autogen or ./configure myself.

**Comment by oco2000** [comment]
Plugin .so is put to /usr/lib/xfce4/panel/plugins, which is ok for Ubuntu at least. I'm not sure that I need to change the defaults. I will put you configure command into README
