### ISSUE TITLE
kbdleds icon not visible, Mint XFCE 20.1 

### ISSUE THREAD

**Issue by MatNieuw** [oco2000/xfce4-kbdleds-plugin#3]
After building is successfully (see issues 1 and 2), it can be installed but there is no icon. Not in "Panel -> Add New Items" or in the "About" properties of the plugin. 
However, if I copy the xfce4-battery-plugin.png in the 32x32 folder to xfce4-kbdleds-plugin.png, the battery icon shows up in "Panel -> Add New Items" . But the "About" still has no icon.
There probably is a spec that says which icons sizes are used when, but I have not found it.
My panel row height is 32 pixels, if I increase to 60 or so it does not make a difference.

**Comment by oco2000** [comment]
I was struggling with the icon a lot )
Unfortunately, I cannot guarantee the visibility, I don't know what's happening with it. On my Ubuntu 20.10 it's fine, but on different distros and versions it magically disappears.

**Comment by MatNieuw** [comment]
I have it working on Mint, except for ru/uk translations.
- I had to add a 32x32 icon (and directories)
- I created a script to make a .deb file, and when installing that says: "Processing triggers for hicolor-icon-theme (0.17-2) ..." . Maybe this is a mandatory action.
- I have not yet succeeded in getting the .mo files installed by the installer.

**Comment by oco2000** [comment]
It actually should update the icon cache after installation, see the `icons/Makefile.am` file.

**Comment by MatNieuw** [comment]
Maybe, but it was erratic. The icon came and went. I have now a stable situation, by generating and installing the 32x32 icon. If you extract the zip in the main directory, if will update 2 files and create a 32x32 directory with makefile and icon. Then a normal build and install sequence will produce a stable situation for me.
[changes_32x32.zip](https://github.com/oco2000/xfce4-kbdleds-plugin/files/5978533/changes_32x32.zip)
The configure command does not need the datarootdir override, so it is sufficient to use
./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu 
The readme.md can be adjusted for that.

Not everyone can or wants to compile on their machine. I am mostly done with a script to create a installable .deb file, only the .mo files need to be done. That .deb file install (and works) fine on machines without any source or development files.

**Comment by oco2000** [comment]
This works for me. Thank you.
Maybe 48x48 is not a standard resolution for the icons
