### ISSUE TITLE
kbdleds Scroll Lock indicator does not react, Mint XFCE 20.1

### ISSUE THREAD

**Issue by MatNieuw** [oco2000/xfce4-kbdleds-plugin#4]
After building and installing xfce4-kbdleds-plugin, the CapsLock and NumLock indicators work fine, but the ScrollLock indicatopr does not react. Standard desktop PC with normal US ASCII keyboard, no extra keys like multimedia.

**Comment by oco2000** [comment]
ScrollLock key is disabled by default in Ubuntu and Mint I guess
Enable it with this command
```
xmodmap -e 'add mod3 = Scroll_Lock'
```

[Source](https://askubuntu.com/questions/764405/scroll-lock-does-not-work)
