### ISSUE TITLE
libkbdleds.la copie to /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/ unnecessary?

### ISSUE THREAD

**Issue by MatNieuw** [oco2000/xfce4-kbdleds-plugin#5]
The install copies the libkbdleds.so file to the proper place (after workaround for issue #2), but it also copies the kbdleds.la file. None of the other plugins do that, is this copy necessary?

**Comment by oco2000** [comment]
As it is said [here](https://lists.gnu.org/archive/html/automake/2011-03/msg00091.html) .la files are needed in certain distributions, so distro maintainers will remove them if necessary.
