### ISSUE TITLE
Please update registration in xfce plugins site

### ISSUE THREAD

**Issue by dioni21** [oco2000/xfce4-kbdleds-plugin#8]
Please update the releases in [xfce plugins site](https://github.com/oco2000/xfce4-kbdleds-plugin)

**Comment by oco2000** [comment]
Your link points to this repo

**Comment by hamlet** [comment]
I guess this is the intended link : https://goodies.xfce.org/projects/panel-plugins/xfce4-kbdleds-plugin
Quite outdated. ;-)

**Comment by oco2000** [comment]
yep, I've lost my credentials and can't login there

**Comment by hamlet** [comment]
Well, goodies.xfce.org is deprecated and read-only. 

> What this means is that active project documentation will be moved, and kept current on docs.xfce.org. Inactive, or deprecated projects will not be migrated. A project is considered deprecated if its files are _not_ currently hosted on the Xfce Git repositories
https://wiki.xfce.org/projects/goodies-decomm/start

No luck linking to this repo from official xfce docs. Too bad.

**Comment by dioni21** [comment]
https://goodies.xfce.org/projects/panel-plugins/xfce4-kbdleds-plugin?do=resendpwd

Doesnt work?
